DATA = objfw-compile.fish	\
       objfw-config.fish	\
       ofarc.fish		\
       ofdns.fish		\
       ofhash.fish		\
       ofhttp.fish

include ../../../buildsys.mk

PACKAGE_NAME = fish/vendor_completions.d
