/*
 * Copyright (c) 2008-2026 Jonathan Schleifer <js@nil.im>
 *
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3.0 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * version 3.0 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3.0 along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* This file is automatically generated from amiga-library.xml */

#include "config.h"

#import "amiga-library.h"
#import "OFObject.h"
#import "OFApplication.h"
#import "OFBlock.h"
#import "OFDNSResourceRecord.h"
#import "OFEmbeddedIRIHandler.h"
#import "OFFileManager.h"
#import "OFHTTPRequest.h"
#import "OFHTTPResponse.h"
#import "OFImage.h"
#import "OFList.h"
#import "OFMethodSignature.h"
#import "OFOnce.h"
#import "OFPBKDF2.h"
#import "OFPlainCondition.h"
#import "OFPlainMutex.h"
#import "OFPlainThread.h"
#import "OFRunLoop.h"
#import "OFScrypt.h"
#import "OFSocket.h"
#import "OFStdIOStream.h"
#import "OFStrPTime.h"
#import "OFString.h"
#import "OFSystemInfo+NetworkInterfaces.h"
#import "OFTLSKey.h"
#import "OFTLSStream.h"
#import "OFX509Certificate.h"
#import "OFZIPArchiveEntry.h"
#import "OFException.h"

extern struct Library *ObjFWBase;

#if OF_GCC_VERSION >= 1100
# pragma GCC diagnostic ignored "-Warray-parameter"
#endif

bool __attribute__((__weak__))
OFInit(unsigned int version, struct OFLinklibContext *_Nonnull ctx)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((bool (*)(unsigned int, struct OFLinklibContext *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 28))(version, ctx);
}

void *_Nullable __attribute__((__weak__))
OFAllocMemory(size_t count, size_t size)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((void *_Nullable (*)(size_t, size_t))*(void **)(((uintptr_t)ObjFWBase) - 34))(count, size);
}

void *_Nullable __attribute__((__weak__))
OFAllocZeroedMemory(size_t count, size_t size)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((void *_Nullable (*)(size_t, size_t))*(void **)(((uintptr_t)ObjFWBase) - 40))(count, size);
}

void *_Nullable __attribute__((__weak__))
OFResizeMemory(void *_Nullable pointer, size_t count, size_t size)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((void *_Nullable (*)(void *_Nullable, size_t, size_t))*(void **)(((uintptr_t)ObjFWBase) - 46))(pointer, count, size);
}

void __attribute__((__weak__))
OFFreeMemory(void *_Nullable pointer)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(void *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 52))(pointer);
}

id _Nonnull __attribute__((__weak__))
OFAllocObject(Class _Nonnull class_, size_t extraSize, size_t extraAlignment, void *_Nullable *_Nullable extra)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((id _Nonnull (*)(Class _Nonnull, size_t, size_t, void *_Nullable *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 58))(class_, extraSize, extraAlignment, extra);
}

void __attribute__((__weak__))
OFMethodNotFound(id _Nonnull self, SEL _Nonnull _cmd)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(id _Nonnull, SEL _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 64))(self, _cmd);

	OF_UNREACHABLE
}

void __attribute__((__weak__))
OFHashInit(unsigned long *_Nonnull hash)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(unsigned long *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 70))(hash);
}

uint16_t __attribute__((__weak__))
OFRandom16()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint16_t (*)())*(void **)(((uintptr_t)ObjFWBase) - 76))();
}

uint32_t __attribute__((__weak__))
OFRandom32()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint32_t (*)())*(void **)(((uintptr_t)ObjFWBase) - 82))();
}

uint64_t __attribute__((__weak__))
OFRandom64()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint64_t (*)())*(void **)(((uintptr_t)ObjFWBase) - 88))();
}

unsigned long *_Nonnull __attribute__((__weak__))
OFHashSeedRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((unsigned long *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 94))();
}

int __attribute__((__weak__))
OFApplicationMain(int *_Nonnull argc, char *_Nullable *_Nonnull *_Nonnull argv, id <OFApplicationDelegate> delegate)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(int *_Nonnull, char *_Nullable *_Nonnull *_Nonnull, id <OFApplicationDelegate>))*(void **)(((uintptr_t)ObjFWBase) - 100))(argc, argv, delegate);
}

void *_Nullable __attribute__((__weak__))
_Block_copy(const void *_Nullable block)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((void *_Nullable (*)(const void *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 106))(block);
}

void __attribute__((__weak__))
_Block_release(const void *_Nullable block)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(const void *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 112))(block);
}

void __attribute__((__weak__))
_Block_object_assign(void *_Nonnull dst, const void *_Nullable src, int flags)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(void *_Nonnull, const void *_Nullable, int))*(void **)(((uintptr_t)ObjFWBase) - 118))(dst, src, flags);
}

void __attribute__((__weak__))
_Block_object_dispose(const void *object, int flags)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(const void *, int))*(void **)(((uintptr_t)ObjFWBase) - 124))(object, flags);
}

OFString *_Nonnull __attribute__((__weak__))
OFDNSClassName(OFDNSClass DNSClass)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(OFDNSClass))*(void **)(((uintptr_t)ObjFWBase) - 130))(DNSClass);
}

OFString *_Nonnull __attribute__((__weak__))
OFDNSRecordTypeName(OFDNSRecordType recordType)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(OFDNSRecordType))*(void **)(((uintptr_t)ObjFWBase) - 136))(recordType);
}

OFDNSClass __attribute__((__weak__))
OFDNSClassParseName(OFString *_Nonnull string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFDNSClass (*)(OFString *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 142))(string);
}

OFDNSRecordType __attribute__((__weak__))
OFDNSRecordTypeParseName(OFString *_Nonnull string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFDNSRecordType (*)(OFString *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 148))(string);
}

void __attribute__((__weak__))
OFRegisterEmbeddedFile(OFString *_Nonnull name, const uint8_t *_Nonnull bytes, size_t size)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFString *_Nonnull, const uint8_t *_Nonnull, size_t))*(void **)(((uintptr_t)ObjFWBase) - 154))(name, bytes, size);
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileSizeRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 160))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileTypeRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 166))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFilePOSIXPermissionsRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 172))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileOwnerAccountIDRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 178))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileGroupOwnerAccountIDRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 184))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileOwnerAccountNameRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 190))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileGroupOwnerAccountNameRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 196))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileLastAccessDateRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 202))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileModificationDateRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 208))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileStatusChangeDateRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 214))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileCreationDateRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 220))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileSymbolicLinkDestinationRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 226))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileExtendedAttributesNamesRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 232))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileAmigaProtectionRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 238))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileAmigaCommentRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 244))();
}

const OFFileAttributeKey *_Nonnull __attribute__((__weak__))
OFFileMSDOSAttributesRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 250))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeRegularRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 256))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeDirectoryRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 262))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeSymbolicLinkRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 268))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeFIFORef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 274))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeCharacterSpecialRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 280))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeBlockSpecialRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 286))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeSocketRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 292))();
}

const OFFileAttributeType *_Nonnull __attribute__((__weak__))
OFFileTypeUnknownRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFFileAttributeType *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 298))();
}

OFString *_Nullable __attribute__((__weak__))
OFHTTPRequestMethodString(OFHTTPRequestMethod method)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nullable (*)(OFHTTPRequestMethod))*(void **)(((uintptr_t)ObjFWBase) - 304))(method);
}

OFHTTPRequestMethod __attribute__((__weak__))
OFHTTPRequestMethodParseString(OFString *string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFHTTPRequestMethod (*)(OFString *))*(void **)(((uintptr_t)ObjFWBase) - 310))(string);
}

OFString *_Nonnull __attribute__((__weak__))
OFHTTPStatusCodeString(short code)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(short))*(void **)(((uintptr_t)ObjFWBase) - 316))(code);
}

const OFImageFormat *_Nonnull __attribute__((__weak__))
OFImageFormatBMPRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFImageFormat *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 322))();
}

const OFImageFormat *_Nonnull __attribute__((__weak__))
OFImageFormatGIFRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFImageFormat *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 328))();
}

const OFImageFormat *_Nonnull __attribute__((__weak__))
OFImageFormatJPEGRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFImageFormat *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 334))();
}

const OFImageFormat *_Nonnull __attribute__((__weak__))
OFImageFormatPNGRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFImageFormat *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 340))();
}

const OFImageFormat *_Nonnull __attribute__((__weak__))
OFImageFormatQOIRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFImageFormat *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 346))();
}

OFListItem _Nullable __attribute__((__weak__))
OFListItemNext(OFListItem _Nonnull listItem)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFListItem _Nullable (*)(OFListItem _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 352))(listItem);
}

OFListItem _Nullable __attribute__((__weak__))
OFListItemPrevious(OFListItem _Nonnull listItem)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFListItem _Nullable (*)(OFListItem _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 358))(listItem);
}

id _Nonnull __attribute__((__weak__))
OFListItemObject(OFListItem _Nonnull listItem)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((id _Nonnull (*)(OFListItem _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 364))(listItem);
}

size_t __attribute__((__weak__))
OFSizeOfTypeEncoding(const char *type)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((size_t (*)(const char *))*(void **)(((uintptr_t)ObjFWBase) - 370))(type);
}

size_t __attribute__((__weak__))
OFAlignmentOfTypeEncoding(const char *type)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((size_t (*)(const char *))*(void **)(((uintptr_t)ObjFWBase) - 376))(type);
}

void __attribute__((__weak__))
OFOnce(OFOnceControl *_Nonnull control, OFOnceFunction _Nonnull func)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFOnceControl *_Nonnull, OFOnceFunction _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 382))(control, func);
}

void __attribute__((__weak__))
OFPBKDF2(OFPBKDF2Parameters parameters)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFPBKDF2Parameters))*(void **)(((uintptr_t)ObjFWBase) - 388))(parameters);
}

int __attribute__((__weak__))
OFPlainConditionNew(OFPlainCondition *_Nonnull condition)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 394))(condition);
}

int __attribute__((__weak__))
OFPlainConditionSignal(OFPlainCondition *_Nonnull condition)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 400))(condition);
}

int __attribute__((__weak__))
OFPlainConditionBroadcast(OFPlainCondition *_Nonnull condition)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 406))(condition);
}

int __attribute__((__weak__))
OFPlainConditionWait(OFPlainCondition *_Nonnull condition, OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull, OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 412))(condition, mutex);
}

int __attribute__((__weak__))
OFPlainConditionTimedWait(OFPlainCondition *_Nonnull condition, OFPlainMutex *_Nonnull mutex, OFTimeInterval timeout)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull, OFPlainMutex *_Nonnull, OFTimeInterval))*(void **)(((uintptr_t)ObjFWBase) - 418))(condition, mutex, timeout);
}

int __attribute__((__weak__))
OFPlainConditionWaitOrExecSignal(OFPlainCondition *_Nonnull condition, OFPlainMutex *_Nonnull mutex, ULONG *_Nonnull signalMask)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull, OFPlainMutex *_Nonnull, ULONG *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 424))(condition, mutex, signalMask);
}

int __attribute__((__weak__))
OFPlainConditionTimedWaitOrExecSignal(OFPlainCondition *_Nonnull condition, OFPlainMutex *_Nonnull mutex, OFTimeInterval timeout, ULONG *_Nonnull signalMask)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull, OFPlainMutex *_Nonnull, OFTimeInterval, ULONG *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 430))(condition, mutex, timeout, signalMask);
}

int __attribute__((__weak__))
OFPlainConditionFree(OFPlainCondition *_Nonnull condition)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainCondition *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 436))(condition);
}

int __attribute__((__weak__))
OFPlainMutexNew(OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 442))(mutex);
}

int __attribute__((__weak__))
OFPlainMutexLock(OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 448))(mutex);
}

int __attribute__((__weak__))
OFPlainMutexTryLock(OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 454))(mutex);
}

int __attribute__((__weak__))
OFPlainMutexUnlock(OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 460))(mutex);
}

int __attribute__((__weak__))
OFPlainMutexFree(OFPlainMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 466))(mutex);
}

int __attribute__((__weak__))
OFPlainRecursiveMutexNew(OFPlainRecursiveMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainRecursiveMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 472))(mutex);
}

int __attribute__((__weak__))
OFPlainRecursiveMutexLock(OFPlainRecursiveMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainRecursiveMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 478))(mutex);
}

int __attribute__((__weak__))
OFPlainRecursiveMutexTryLock(OFPlainRecursiveMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainRecursiveMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 484))(mutex);
}

int __attribute__((__weak__))
OFPlainRecursiveMutexUnlock(OFPlainRecursiveMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainRecursiveMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 490))(mutex);
}

int __attribute__((__weak__))
OFPlainRecursiveMutexFree(OFPlainRecursiveMutex *_Nonnull mutex)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainRecursiveMutex *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 496))(mutex);
}

int __attribute__((__weak__))
OFPlainThreadAttributesInit(OFPlainThreadAttributes *_Nonnull attr)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainThreadAttributes *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 502))(attr);
}

int __attribute__((__weak__))
OFPlainThreadNew(OFPlainThread _Nonnull *_Nonnull thread, const char *_Nullable name, OFPlainThreadFunction _Nonnull function, id _Nullable object, const OFPlainThreadAttributes *_Nullable attr)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainThread _Nonnull *_Nonnull, const char *_Nullable, OFPlainThreadFunction _Nonnull, id _Nullable, const OFPlainThreadAttributes *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 508))(thread, name, function, object, attr);
}

void __attribute__((__weak__))
OFSetThreadName(const char *_Nullable name)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(const char *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 514))(name);
}

int __attribute__((__weak__))
OFPlainThreadJoin(OFPlainThread _Nonnull thread)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainThread _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 520))(thread);
}

int __attribute__((__weak__))
OFPlainThreadDetach(OFPlainThread _Nonnull thread)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFPlainThread _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 526))(thread);
}

OFPlainThread _Nonnull __attribute__((__weak__))
OFCurrentPlainThread()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFPlainThread _Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 532))();
}

bool __attribute__((__weak__))
OFPlainThreadIsCurrent(OFPlainThread _Nonnull thread)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((bool (*)(OFPlainThread _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 538))(thread);
}

const OFRunLoopMode *_Nonnull __attribute__((__weak__))
OFDefaultRunLoopModeRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFRunLoopMode *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 544))();
}

void __attribute__((__weak__))
OFScrypt(OFScryptParameters parameters)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFScryptParameters))*(void **)(((uintptr_t)ObjFWBase) - 550))(parameters);
}

void __attribute__((__weak__))
_OFSalsa20_8Core(uint32_t *_Nonnull buffer)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(uint32_t *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 556))(buffer);
}

void __attribute__((__weak__))
_OFScryptBlockMix(uint32_t *_Nonnull output, const uint32_t *_Nonnull input, size_t blockSize)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(uint32_t *_Nonnull, const uint32_t *_Nonnull, size_t))*(void **)(((uintptr_t)ObjFWBase) - 562))(output, input, blockSize);
}

void __attribute__((__weak__))
_OFScryptROMix(uint32_t *buffer, size_t blockSize, size_t costFactor, uint32_t *tmp)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(uint32_t *, size_t, size_t, uint32_t *))*(void **)(((uintptr_t)ObjFWBase) - 568))(buffer, blockSize, costFactor, tmp);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressParseIP(OFString *_Nonnull IP, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(OFString *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 574))(IP, port);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressParseIPv4(OFString *_Nonnull IP, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(OFString *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 580))(IP, port);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressParseIPv6(OFString *_Nonnull IP, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(OFString *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 586))(IP, port);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressMakeUNIX(OFString *_Nonnull path)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(OFString *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 592))(path);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressMakeIPX(uint32_t network, const unsigned char *_Nonnull node, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(uint32_t, const unsigned char *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 598))(network, node, port);
}

OFSocketAddress __attribute__((__weak__))
OFSocketAddressMakeAppleTalk(uint16_t network, uint8_t node, uint8_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFSocketAddress (*)(uint16_t, uint8_t, uint8_t))*(void **)(((uintptr_t)ObjFWBase) - 604))(network, node, port);
}

bool __attribute__((__weak__))
OFSocketAddressEqual(const OFSocketAddress *_Nonnull address1, const OFSocketAddress *_Nonnull address2)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((bool (*)(const OFSocketAddress *_Nonnull, const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 610))(address1, address2);
}

unsigned long __attribute__((__weak__))
OFSocketAddressHash(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((unsigned long (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 616))(address);
}

OFString *_Nonnull __attribute__((__weak__))
OFSocketAddressString(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 622))(address);
}

OFString *_Nonnull __attribute__((__weak__))
OFSocketAddressDescription(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 628))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetIPPort(OFSocketAddress *_Nonnull address, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 634))(address, port);
}

uint16_t __attribute__((__weak__))
OFSocketAddressIPPort(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint16_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 640))(address);
}

OFString * __attribute__((__weak__))
OFSocketAddressUNIXPath(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *(*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 646))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetIPXNetwork(OFSocketAddress *_Nonnull address, uint32_t network)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint32_t))*(void **)(((uintptr_t)ObjFWBase) - 652))(address, network);
}

uint32_t __attribute__((__weak__))
OFSocketAddressIPXNetwork(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint32_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 658))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetIPXNode(OFSocketAddress *_Nonnull address, const unsigned char *_Nonnull node)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, const unsigned char *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 664))(address, node);
}

void __attribute__((__weak__))
OFSocketAddressGetIPXNode(const OFSocketAddress *_Nonnull address, unsigned char *_Nonnull node)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(const OFSocketAddress *_Nonnull, unsigned char *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 670))(address, node);
}

void __attribute__((__weak__))
OFSocketAddressSetIPXPort(OFSocketAddress *_Nonnull address, uint16_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 676))(address, port);
}

uint16_t __attribute__((__weak__))
OFSocketAddressIPXPort(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint16_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 682))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetAppleTalkNetwork(OFSocketAddress *_Nonnull address, uint16_t network)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 688))(address, network);
}

uint16_t __attribute__((__weak__))
OFSocketAddressAppleTalkNetwork(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint16_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 694))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetAppleTalkNode(OFSocketAddress *_Nonnull address, uint8_t node)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint8_t))*(void **)(((uintptr_t)ObjFWBase) - 700))(address, node);
}

uint8_t __attribute__((__weak__))
OFSocketAddressAppleTalkNode(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint8_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 706))(address);
}

void __attribute__((__weak__))
OFSocketAddressSetAppleTalkPort(OFSocketAddress *_Nonnull address, uint8_t port)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFSocketAddress *_Nonnull, uint8_t))*(void **)(((uintptr_t)ObjFWBase) - 712))(address, port);
}

uint8_t __attribute__((__weak__))
OFSocketAddressAppleTalkPort(const OFSocketAddress *_Nonnull address)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((uint8_t (*)(const OFSocketAddress *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 718))(address);
}

OFStdIOStream *_Nonnull *_Nullable __attribute__((__weak__))
OFStdInRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFStdIOStream *_Nonnull *_Nullable (*)())*(void **)(((uintptr_t)ObjFWBase) - 724))();
}

OFStdIOStream *_Nonnull *_Nullable __attribute__((__weak__))
OFStdOutRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFStdIOStream *_Nonnull *_Nullable (*)())*(void **)(((uintptr_t)ObjFWBase) - 730))();
}

OFStdIOStream *_Nonnull *_Nullable __attribute__((__weak__))
OFStdErrRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFStdIOStream *_Nonnull *_Nullable (*)())*(void **)(((uintptr_t)ObjFWBase) - 736))();
}

void __attribute__((__weak__))
OFLogV(OFConstantString *_Nonnull format, va_list arguments)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)(OFConstantString *_Nonnull, va_list))*(void **)(((uintptr_t)ObjFWBase) - 742))(format, arguments);
}

const char *_Nullable __attribute__((__weak__))
_OFStrPTime(const char *buffer, const char *format, struct tm *tm, int16_t *_Nullable tz)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const char *_Nullable (*)(const char *, const char *, struct tm *, int16_t *_Nullable))*(void **)(((uintptr_t)ObjFWBase) - 748))(buffer, format, tm, tz);
}

OFStringEncoding __attribute__((__weak__))
OFStringEncodingParseName(OFString *_Nonnull string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFStringEncoding (*)(OFString *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 754))(string);
}

OFString *_Nullable __attribute__((__weak__))
OFStringEncodingName(OFStringEncoding encoding)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nullable (*)(OFStringEncoding))*(void **)(((uintptr_t)ObjFWBase) - 760))(encoding);
}

size_t __attribute__((__weak__))
OFUTF16StringLength(const OFChar16 *_Nonnull string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((size_t (*)(const OFChar16 *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 766))(string);
}

size_t __attribute__((__weak__))
OFUTF32StringLength(const OFChar32 *_Nonnull string)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((size_t (*)(const OFChar32 *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 772))(string);
}

const OFNetworkInterfaceKey *_Nonnull __attribute__((__weak__))
OFNetworkInterfaceIndexRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFNetworkInterfaceKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 778))();
}

const OFNetworkInterfaceKey *_Nonnull __attribute__((__weak__))
OFNetworkInterfaceHardwareAddressRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFNetworkInterfaceKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 784))();
}

const OFNetworkInterfaceKey *_Nonnull __attribute__((__weak__))
OFNetworkInterfaceIPv4AddressesRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((const OFNetworkInterfaceKey *_Nonnull (*)())*(void **)(((uintptr_t)ObjFWBase) - 790))();
}

int __attribute__((__weak__))
OFTLSKeyNew(OFTLSKey _Nonnull *_Nonnull key)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFTLSKey _Nonnull *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 796))(key);
}

int __attribute__((__weak__))
OFTLSKeyFree(OFTLSKey _Nonnull key)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((int (*)(OFTLSKey _Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 802))(key);
}

Class _Nonnull *_Nullable __attribute__((__weak__))
OFTLSStreamImplementationRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((Class _Nonnull *_Nullable (*)())*(void **)(((uintptr_t)ObjFWBase) - 808))();
}

OFString * __attribute__((__weak__))
OFTLSStreamErrorCodeDescription(OFTLSStreamErrorCode errorCode)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *(*)(OFTLSStreamErrorCode))*(void **)(((uintptr_t)ObjFWBase) - 814))(errorCode);
}

Class _Nonnull *_Nullable __attribute__((__weak__))
OFX509CertificateImplementationRef()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((Class _Nonnull *_Nullable (*)())*(void **)(((uintptr_t)ObjFWBase) - 820))();
}

OFString *_Nonnull __attribute__((__weak__))
OFZIPArchiveEntryVersionToString(uint16_t version)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(uint16_t))*(void **)(((uintptr_t)ObjFWBase) - 826))(version);
}

OFString *_Nonnull __attribute__((__weak__))
OFZIPArchiveEntryCompressionMethodName(OFZIPArchiveEntryCompressionMethod compressionMethod)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(OFZIPArchiveEntryCompressionMethod))*(void **)(((uintptr_t)ObjFWBase) - 832))(compressionMethod);
}

size_t __attribute__((__weak__))
OFZIPArchiveEntryExtraFieldFind(OFData *_Nonnull extraField, OFZIPArchiveEntryExtraFieldTag tag, uint16_t *_Nonnull size)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((size_t (*)(OFData *_Nonnull, OFZIPArchiveEntryExtraFieldTag, uint16_t *_Nonnull))*(void **)(((uintptr_t)ObjFWBase) - 838))(extraField, tag, size);
}

OFString *_Nonnull __attribute__((__weak__))
OFStrError(int errNo)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	return __extension__ ((OFString *_Nonnull (*)(int))*(void **)(((uintptr_t)ObjFWBase) - 844))(errNo);
}

void __attribute__((__weak__))
_OFThrowOutOfRangeException()
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWBase) : "r12"
	);

	__extension__ ((void (*)())*(void **)(((uintptr_t)ObjFWBase) - 850))();

	OF_UNREACHABLE
}
