PLUGIN_NOINST = TestPlugin${PLUGIN_SUFFIX}
SRCS = TestPlugin.m

include ../../../buildsys.mk
include ../../../extra.mk

CPPFLAGS += ${PLUGIN_CPPFLAGS} -I../../../src
OBJCFLAGS += ${PLUGIN_CFLAGS}
LDFLAGS += ${PLUGIN_LDFLAGS}
