/*
 * Copyright (c) 2008-2026 Jonathan Schleifer <js@nil.im>
 *
 * All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3.0 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 * version 3.0 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3.0 along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* This file is automatically generated from amiga-library.xml */

#include "config.h"

#import "amiga-library.h"

struct Library *ObjFWTLSBase;

#if OF_GCC_VERSION >= 1100
# pragma GCC diagnostic ignored "-Warray-parameter"
#endif

bool __attribute__((__weak__))
OFTLSInit(unsigned int version, struct OFTLSLinklibContext *_Nonnull ctx)
{
	__asm__ __volatile__ (
	    "mr		%%r12, %0"
	    :: "r" (ObjFWTLSBase) : "r12"
	);

	return __extension__ ((bool (*)(unsigned int, struct OFTLSLinklibContext *_Nonnull))*(void **)(((uintptr_t)ObjFWTLSBase) - 28))(version, ctx);
}
