.TH OBJFW-COMPILE 1
.SH NAME
objfw-compile - compile simple projects using ObjFW
.SH SYNOPSIS
.B objfw-config
[\fBoptions\fR]
\fB\-o\fR \fIoutname\fR
\fIsources\fR
.SH DESCRIPTION
.B objfw-compile
is a program to compile simple projects using ObjFW.
.SH OPTIONS
.TP
.BR \-o " " \fIoutname\fR
Specify the output name (not the file name!).
.TP
.BR \-\-arc
Use automatic reference counting.
.TP
.BR \-\-lib " " \fIversion\fR
Compile a static library (with the specified version) instead of an application.
.TP
.BR \-\-plugin
Compile a plugin instead of an application.
.TP
.BR \-\-package " " \fIname\fR
Use the specified package.
.TP
.BR \-\-builddir " " \fIdir\fR
Place built objects into the specified directory.
.TP
.BR \-D\fIdefine\fR ", " \-D " " \fIdefine\fR
Pass the specified define to the compiler.
.TP
.BR \-framework " " \fIframework\fR
Pass the specified -framework argument to the linker (macOS / iOS only).
.TP
.BR \-f\fIflag\fR
Pass the specified -f flag to the compiler.
.TP
.BR \-F\fIdir\fR ", " \-F " " \fIdir\fR
Pass the specified -F flag to the linker (macOS / iOS only).
.TP
.BR \-g\fIflag\fR
Pass the specified -g flag to the compiler.
.TP
.BR \-I\fIdir\fR ", " \-I " " \fIdir\fR
Pass the specified -I flag to the compiler.
.TP
.BR \-l\fIlib\fR ", " \-l " " \fIlib\fR
Pass the specified -l flag to the linker.
.TP
.BR \-L\fIdir\fR ", " \-L " " \fIdir\fR
Pass the specified -L flag to the linker.
.TP
.BR \-m\fIflag\fR
Pass the specified -m flag to the compiler.
.TP
.BR \-O\fIlevel\fR
Pass the specified -O flag to the compiler.
.TP
.BR \-pthread
Pass -pthread to the compiler and linker.
.TP
.BR \-std=\fIlang\fR
Pass the specified -std= flag to the compiler.
.TP
.BR \-Wl,\fIflag\fR
Pass the specified -Wl, flag to the linker.
.TP
.BR \-W\fIwarning\fR
Pass the specified -W flag to the compiler.
.TP
.BR \-\-help
Show the help.
.SH EXAMPLES
Compile a program with two source files:
.PP
	objfw-compile -o myprog MyProg.m SomeClass.m
.PP
Compile a library with library version 1.0:
.PP
	objfw-compile --lib 1.0 -o mylib Class1.m Class2.m
.SH SEE ALSO
\fIobjfw-config\fR(1)
