name: msys2
on: [push, pull_request]
jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - mingw64
          - ucrt64
          - clang64
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{matrix.sys}}
          install: autoconf automake make
          pacboy: clang:p openssl:p
      - name: autogen.sh
        shell: msys2 {0}
        run: ./autogen.sh
      - name: configure
        shell: msys2 {0}
        run: ./configure OBJC=clang
      - name: make
        shell: msys2 {0}
        run: make -j4
      - name: make check
        shell: msys2 {0}
        run: make check
      - name: make install
        shell: msys2 {0}
        run: make install
      - name: C++ test
        shell: msys2 {0}
        run: |
          objfw-compile -o cxxtest .github/workflows/CXXTest.mm
          ./cxxtest.exe
